export const GET_CURRENCY_REQUEST = "GET_CURRENCY_REQUEST"
export const GET_CURRENCY_SUCCESS = "GET_CURRENCY_SUCCESS"

export const GET_PAGE_REQUEST = "GET_PAGE_REQUEST"
export const GET_PAGE_SUCCESS = "GET_PAGE_SUCCESS"